### ISSUE TITLE
Console Error on window resize after closing easyannotation

### ISSUE THREAD

**Issue by LauraTink** [abeleuta/easyannotation#21]
Console Error on window resize after closing easyannotation

Steps to reproduce:

1.  Have the close button visible in the config
2.  Click close on easyannotation
3.  Have developer tools open (F12)
4.  Resize window, error will appear in console logs.

When closing easyannotation the window resize event listener still exists calling `doLayout()` which is where the error is coming from. 

![image](https://user-images.githubusercontent.com/42024009/132649274-2c0941ef-959d-4060-aa9a-7da3f8a57777.png)

I have pulled the code and found the following is needed to resolve the issue. Firstly adding a remove event listener inside the close function.
`window.removeEventListener("resize", this.onResize);`

```
  public close() {
    window.removeEventListener("resize", this.onResize);

    this.targetElement.removeChild(this.container);
    if (this.isImageElement) {
      this.imageElement.style.visibility = "visible";
    }

    let targetElement = this.config.targetElement;
    if (this.toolbar) {
      targetElement.removeChild(this.toolbar.getContainer());
    }

    if (this.propertiesToolbar) {
      targetElement.removeChild(this.propertiesToolbar.getContainer());
    }
  }
```

This then causes multiple close buttons to be pushed to the toolbar when calling the show function. To resolve this issue, where the close icon button is added to the toolbar, check the current list of toolbar icons to make sure close is undefined before pushing another close icon button within the initToolbar function.

```
        if (config.showClose === true && toolbarItems.find((x) => x.itemId === "close") === undefined) {
          toolbarItems.push({
            itemId: "close",
            iconSVG: CloseIcon,
            title: "Close Annotator",
          });
        }
```

```
        if (config.showClose === true && !haveClose && toolbarItems.find((x) => x.itemId === "close") === undefined) {
          toolbarItems.push({
            itemId: "close",
            iconSVG: CloseIcon,
            title: "Close Annotator",
          });
        }
```

**Comment by abeleuta** [comment]
Thanks for the issue. This is fixed now.
