### ISSUE TITLE
Default options for Fill transparency control overall element visibility

### ISSUE THREAD

**Issue by LauraTink** [abeleuta/easyannotation#29]
![image](https://user-images.githubusercontent.com/42024009/144036140-8e9fb9dc-789a-4bea-b637-cce418f38e4c.png)

When setting fill opacity to 0, the element is hidden. The value updates the overall transparency slider, not the fill colour transparency slider. 

![easyannotation - bug](https://user-images.githubusercontent.com/42024009/144042306-6bb214e4-367b-4245-beeb-22281e86dace.gif)

**Comment by abeleuta** [comment]
Hello,

Opacity property controls element opacity, so if this is set to 0, element is hidden.
Fill transparency can be set using the color dialog, which has the transparency slider.
