### ISSUE TITLE
Custom styles are ignored

### ISSUE THREAD

**Issue by LauraTink** [abeleuta/easyannotation#31]
As of V2.0.2 the user can no longer add a class and style easy annotation toolbars/ annotator container. 

![FireShot Capture 002 - Easy Annotation - a JavaScript Image Annotation Library - easyannotation com](https://user-images.githubusercontent.com/42024009/145189349-b73f0e07-5ff6-49bf-9175-be13d1ef1008.png)

**Comment by abeleuta** [comment]
Thank you for the issues.

This is because V2 of EasyAnnotation use CSS shadows so annotation styles do not interference with other user defined styles.
Because of this defined styles outside of easy-annotation tag are ignored.

This can be achieved now with CSS parts as below:

```
    easy-annotation::part(toolbar) {
        background-color: #7ff87f !important;
    }
    
    easy-annotation::part(toolbar) svg * {
        fill: #1805A4 !important;
        stroke: #1805A4 !important;
    }
```

**Comment by JoeMellon** [comment]
@abeleuta Hi - Seems the above decs are no longer targeting the SVG correctly - I've tried a few things to no avail, is there any simple way to target these fill props?

Thank you :)
