### ISSUE TITLE
Styling elements off

### ISSUE THREAD

**Issue by xmkan** [abeleuta/easyannotation#5]
Hi,

I am having issues while trying to use this library for my app. The toolbar and style of the plugin goes out of alignment... Is there any work around for this issue? 

![image](https://user-images.githubusercontent.com/26382375/100989061-5f44c200-358b-11eb-974c-b34d7098acac.png)

![image](https://user-images.githubusercontent.com/26382375/100990852-5523c300-358d-11eb-9c8d-052ceed77f29.png)

**Comment by xmkan** [comment]
Hi sorry, 

I am also trying to load the previously saved data but encountered the error below: 
![image](https://user-images.githubusercontent.com/26382375/101013037-aab49b80-359e-11eb-99ef-b0dea084a6f1.png)

And below is my codes that I have implemented: 
`let jsonText = JSON.stringify({
    v: "1.0",
    data: [
      {
        xtype: "ellipse",
        cx: 655,
        cy: 356.5,
        rx: 50,
        ry: 50,
        dw: 2,
        dt: 0,
        dc: "#000",
        sa: 0,
        ea: 0,
        ft: 0,
        fc: "#8EB9ED",
        op: 100,
      },
    ],
  });`

`let annotation2 = new easyannotation.AnnotatorContainer(
      document.querySelector("#plan"),
      {
        loadOnClick: true,
      }
    );
    var previouslySavedJSON;
    annotation2.show(function (res) {
      console.log(res);
      previouslySavedJSON = res;
    }, easyannotation.ExportType.JSON);
    annotation2.loadJSON(jsonText);`

can you please help to see if there is anything wrong? Thank you!

**Comment by xmkan** [comment]
Hi, 

Sorry. I managed to solved the issues above by downloading your CSS found in the github folder and correction of the json string. However, I think there might be a bug while using touch screen devices, the erase function will just erase everything away instead of the selected items but it works fine in web browser. Can you please take a look at this bug? I would really like to use the library features in my project. Thank you!

**Comment by abeleuta** [comment]
Thanks for sharing, I will try to replicate and will fix this.

**Comment by xmkan** [comment]
Hi,

Thank you for your prompt reply!
Is there a way for me to save the results in 2 format at the same time as well? like for base4PNG and also in JSON format? I cant seem to find it in the documentation...

**Comment by abeleuta** [comment]
Method save of AnnotatorContainer has a callback and an export type parameters.
You can call this method many times with different parameters and data will be saved in different formats.
